// Generated by CoffeeScript 1.4.0
(function() {
  var StyleConv, TallyMarks,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TallyMarks = (function() {

    function TallyMarks() {
      this.changeEvent = __bind(this.changeEvent, this);
      this.bind_events();
    }

    TallyMarks.prototype.bind_events = function() {
      $('.tally').on('DOMSubtreeModified', this.changeEvent);
      return $('.tally').trigger('DOMSubtreeModified');
    };

    TallyMarks.prototype.changeEvent = function(e) {
      return this.doTally($(e.currentTarget));
    };

    TallyMarks.prototype.doTally = function($el) {
      var change, classString, cssObject, fives, i, new_val, next, val;
      val = parseInt($el.text());
      if (isNaN(val)) {
        val = 0;
      }
      fives = parseInt(val / 5);
      change = Math.abs(val % 5);
      next = $el.next();
      if ($(next).hasClass('tally-mark')) {
        $(next).remove();
      }
      new_val = "" + (((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= fives ? _i < fives : _i > fives; i = 0 <= fives ? ++_i : --_i) {
          _results.push(5);
        }
        return _results;
      })()).join('')) + (change === 0 ? '' : change);
      cssObject = new StyleConv($el.attr("style")).asObject();
      classString = $el.attr("class");
      return $el.after($('<span>').css(cssObject).addClass(classString).addClass("tally-mark").text(new_val));
    };

    return TallyMarks;

  })();

  StyleConv = (function() {

    function StyleConv(style) {
      this.style = style || '';
    }

    StyleConv.prototype.asArray = function() {
      var _ref;
      return (_ref = this.styleArray) != null ? _ref : this.styleArray = this.style.replace(/;\s*$/, '').split(/[:; ]+/);
    };

    StyleConv.prototype.asObject = function() {
      var i, o;
      i = 0;
      o = {};
      while (this.asArray().length > i + 1) {
        o[this.asArray()[i]] = this.asArray()[i + 1];
        i += 2;
      }
      return o;
    };

    return StyleConv;

  })();

  window.TallyMarks = TallyMarks;

  jQuery(function() {
    return window.tally_marks = new TallyMarks();
  });

}).call(this);
