// Generated by CoffeeScript 1.4.0
(function() {
  var TallyMarks,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TallyMarks = (function() {

    function TallyMarks() {
      this.changeEvent = __bind(this.changeEvent, this);
      this.bind_events();
    }

    TallyMarks.prototype.bind_events = function() {
      $('.tally').on('DOMSubtreeModified', this.changeEvent);
      return $('.tally').trigger('DOMSubtreeModified');
    };

    TallyMarks.prototype.changeEvent = function(e) {
      return this.doTally($(e.currentTarget));
    };

    TallyMarks.prototype.doTally = function($el) {
      var change, fives, i, sibling, val, _i, _j, _len, _ref, _results;
      val = parseInt($el.text());
      if (isNaN(val)) {
        return;
      }
      fives = parseInt(val / 5);
      change = val % 5;
      _ref = $el.siblings();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sibling = _ref[_i];
        if (!$(sibling).hasClass('tally-mark')) {
          break;
        }
        $(sibling).remove();
      }
      if (change !== 0) {
        $el.after($('<span>').addClass("tally-mark").text(change));
      }
      _results = [];
      for (i = _j = 0; 0 <= fives ? _j < fives : _j > fives; i = 0 <= fives ? ++_j : --_j) {
        _results.push($el.after($('<span>').addClass("tally-mark").text(5)));
      }
      return _results;
    };

    return TallyMarks;

  })();

  window.TallyMarks = TallyMarks;

  jQuery(function() {
    return window.tally_marks = new TallyMarks();
  });

}).call(this);
