// Generated by CoffeeScript 1.4.0
(function() {
  var TallyMarks,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TallyMarks = (function() {

    function TallyMarks() {
      this.changeEvent = __bind(this.changeEvent, this);
      this.bind_events();
    }

    TallyMarks.prototype.bind_events = function() {
      $('.tally').on('DOMSubtreeModified', this.changeEvent);
      return $('.tally').trigger('DOMSubtreeModified');
    };

    TallyMarks.prototype.changeEvent = function(e) {
      return this.doTally($(e.currentTarget));
    };

    TallyMarks.prototype.doTally = function($el) {
      var $hashEl, change, fives, i, new_val, next, val;
      val = parseInt($el.text());
      if (isNaN(val)) {
        val = 0;
      }
      fives = parseInt(val / 5);
      change = Math.abs(val % 5);
      next = $el.next();
      if ($(next).hasClass('tally-mark')) {
        $(next).remove();
      }
      new_val = "" + (((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= fives ? _i < fives : _i > fives; i = 0 <= fives ? ++_i : --_i) {
          _results.push(5);
        }
        return _results;
      })()).join('')) + (change === 0 ? '' : change);
      $hashEl = $el.after($('<span>').addClass($el.attr("class")).addClass("tally-mark").text(new_val));
      return $hashEl.css($el.attr("style") || '');
    };

    return TallyMarks;

  })();

  window.TallyMarks = TallyMarks;

  jQuery(function() {
    return window.tally_marks = new TallyMarks();
  });

}).call(this);
